=== sparkslabs/kamaelia/branches/private_MH_20070618_docgen_improvements/Sketches/MH/MobileReframe/MobileReframe.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : MobileReframe.xsd
    Created on : 13 September 2006, 12:00
    Author     : Steve Jolly
    Description:
        An Edit Decision List document for mobile reframing.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:mr="http://www.rd.bbc.co.uk/rp/MobileReframe"
    targetNamespace="http://www.rd.bbc.co.uk/rp/MobileReframe"
    xmlns="http://www.rd.bbc.co.uk/rp/MobileReframe"
    elementFormDefault="qualified">

    <xsd:element name="EDL" type="mr:EDLType">
        <xsd:annotation>
            <xsd:documentation>A document conforming to the Edit Decision List schema specified for the MobileReframe prototype.</xsd:documentation>
        </xsd:annotation>
    </xsd:element>
    <xsd:complexType name="EDLType">
        <xsd:sequence>
            <xsd:element name="FileID" type="xsd:string"/>
            <xsd:element name="Edit" type="mr:EditType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="EditType">
        <xsd:sequence>
            <xsd:element name="Start" type="mr:PositionType"/>
            <xsd:element name="End" type="mr:PositionType"/>
            <xsd:element name="Crop" type="mr:BoxType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="PositionType">
        <xsd:attribute name="frame" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="BoxType">
        <xsd:attribute name="x1" type="xsd:integer"/>
        <xsd:attribute name="y1" type="xsd:integer"/>
        <xsd:attribute name="x2" type="xsd:integer"/>
        <xsd:attribute name="y2" type="xsd:integer"/>
    </xsd:complexType>
</xsd:schema>

=== sparkslabs/kamaelia/branches/private_PT_WindowsBugfixes/Sketches/MH/MobileReframe/TestEDL.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<EDL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MobileReframe.xsd">>
    <FileID>File identifier</FileID>
    
    <Edit>
        <Start frame="0"  />
        <End   frame="24" />
        <Crop  x1="0" y1="0" x2="400" y2="100" />
    </Edit>
    <Edit>
        <Start frame="25" />
        <End   frame="49" />
        <Crop  x1="80" y1="40" x2="480" y2="140" />
    </Edit>
</EDL>
